# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=212)),
                ('description', models.TextField()),
                ('admins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='users.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('place', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('going', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='users.CustomUser')),
                ('notGoing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avoiding', to='users.CustomUser')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='events',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='community.Event'),
        ),
        migrations.AddField(
            model_name='community',
            name='followers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='users.CustomUser'),
        ),
    ]
