# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='events',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='community.Event'),
        ),
        migrations.AlterField(
            model_name='community',
            name='followers',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='users.CustomUser'),
        ),
    ]
