# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20170210_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='followers',
        ),
    ]
